apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: log-anomaly
type: Opaque
data:
  mongo-root-username: YWRtaW4=
  mongo-root-password: YWRtaW4=
  mongo-initdb-database: bG9nc19kYg==
